name: cus_theme
description: "A customizable Flutter theme package with light/dark modes, color presets, typography, spacing, and dynamic theme switching."
version: 1.8.1
homepage: https://nocorps.org/
repository: https://github.com/KANAGARAJ-M/cus_theme
issue_tracker: https://github.com/KANAGARAJ-M/cus_theme/issues



environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

 